"""init_table

Revision ID: 883d0a639f4a
Revises: 
Create Date: 2023-05-29 07:17:23.286828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883d0a639f4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_question', sa.String(), nullable=True),
    sa.Column('text_answer', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_id'), 'quiz', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_id'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
